apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podmonitor-pod
  labels:
    monitor: pod 
spec:
  selector:
    matchLabels:
      app: "pod-deployment"
  podMetricsEndpoints:
  - port: "pod"
  namespaceSelector:
    matchNames:
      - podmonitor-test
