apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  serviceAccountName: prometheus-svc-acc
  resources:
    requests:
      memory: 200Mi
      cpu: 2
