apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-prom
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 30s
    port: 'web'
  selector:
    matchLabels:
      metrics: "service"
  namespaceSelector:
    any: true
